```{r, eval=FALSE}
frq(main, Est_avail, sort.frq = "none")
```

```{r, echo = TRUE, results = 'asis'}
summarytools::descr(main$Est_tunit_n, 
                    stats = c("mean", "sd", "min", "med", "max"), 
                    round.digits = 1, omit.headings = TRUE, style = "rmarkdown")
```


#### Frequent authors

Authors with more than 2 works

```{r}
main %>% select(FA_surname, starts_with("Author")) %>% 
  rename(Author_1 = FA_surname) %>% 
  gather(Position, Surname, Author_1:Author_16) %>% 
  filter(Surname != "") %>% 
  mutate(Surname = str_replace(Surname, fixed("*"), "")) %>% 
  group_by(Surname) %>% 
  summarise(Freq = n()) %>% 
  filter(Freq > 2) %>% 
  arrange(desc(Freq))
```


#### Frequent journals

Journals with more than one appearance

```{r}
main %>% 
  filter(Pub_type == "article") %>% 
  group_by(Journal_name) %>% 
  summarise(Freq = n()) %>% 
  filter(Freq > 1) %>% 
  arrange(desc(Freq))
```

#### Temporal breakdown

```{r, eval=FALSE}
frq(main, Year_pub, sort.frq = "none")
```

```{r}
ggplot(main, aes(Year_pub)) + 
  geom_histogram(aes(y = stat(count)), binwidth = 1) +
  theme_minimal() + 
  labs(x = "Year of publication",
       y = "Number of studies",
       title = "Distribution of year of publication")
```

#### Thematic breakdown

```{r, eval=FALSE}
main %>% select(Year_pub, starts_with("Type_")) %>% 
  gather(Order, Type, Type_1:Type_3) %>% 
  filter(Type != "") %>% 
  frq(Type, sort.frq = "desc")
```

```{r}
main %>% select(Year_pub, starts_with("Type_")) %>% 
  gather(Order, Type, Type_1:Type_3) %>% 
  filter(Type != "") %>% 
  ggplot(aes(fct_infreq(Type))) +
  geom_bar() +
  theme_minimal() + 
  labs(x = "Main type of data used",
       y = "Number of studies",
       title = "Main type of data used in publication",
       caption = "Study can belong to more than one category. See main text for abbreviations of types.")
```