---
title: "Estimating temporary populations: a systematic review of the empirical literature"
subtitle: "Appendix 4: Main characteristics of the studies"
author: "Radoslaw Panczak, Elin Charles-Edwards, Jonathan Corcoran"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  bookdown::html_document2:
    highlight: pygments
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 4
    # toc_float: yes
header-includes: 
  - \pagenumbering{gobble}
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(pacman)
p_load(tidyverse, readxl, kableExtra)

```

```{r data, include=FALSE}
main <- read_excel("./data/TEMPO_SR_2019-10-22.xlsx", sheet = "Main") %>% 
  replace(is.na(.), "")
```

# Source, type, purpose, main data and methods 

```{r}
main %>% 
  select(FA_surname, Year_pub, 
         Source, Pub_type, 
         Purpose_1, Purpose_2, 
         Type_1, Type_2, Type_3, Type_4, 
         Method) %>% 
  kable(col.names = c("Author",
                      "Year of publication",
                      "Source",
                      "Type of publication",
                      "Purpose (1)",  
                      "Purpose (2)",  
                      "Main data (1)",
                      "Main data (2)",
                      "Main data (3)",
                      "Main data (4)",
                      "Methods")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

# Other characteristics 

```{r}
main %>% 
  select(FA_surname, Year_pub,
         National, Country_1, Country_2, Region_type, Region,
         Day, Est_tunit, Est_tunit_num, 
         Data_size_users, Est_pop_size, 
         Est_unit_type_1, Est_unit_type_2	, Est_spat_num_1, Est_spat_num_2, 
         Validation, Software_avail, Est_avail) %>% 
  kable(col.names = c("Author",
                      "Year of publication",
                      "National coverage", 
                      "Country (1)", "Country (2)", 
                      "Type of Region", 
                      "Name of Region",
                      "Daytime estimates", 
                      "Type of temporal unit", 
                      "Number of temporal unit", 
                      "Size of population (data)", 
                      "Size of population (estimated)", 
                      "Spatial unit for estimated populations (1)",
                      "Spatial unit for estimated populations (2)",
                      "Number of spatial units for estimated population (1)", 
                      "Number of spatial units for estimated population (2)", 
                      "Was validation of the estimates carried out?", 
                      "Is software used for the estimation avaiable?", 
                      "Are the estimates avaiable for download?")) %>%  
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```



